"""
Design System Registry
54 design systems from popular-web-designs skill, with metadata for selection.
"""

DESIGN_SYSTEMS = {
    # ============================================================
    # AI & Machine Learning
    # ============================================================
    "claude": {
        "name": "Claude",
        "site": "Anthropic",
        "category": "AI & ML",
        "description": "Warm terracotta accent, clean editorial layout",
        "tags": ["ai", "warm", "editorial", "minimal"],
        "mood": "温暖克制，有深度",
        "recommended_for": ["AI从业者", "思想领袖", "内容创作者"],
        "font_primary": "Inter",
        "font_mono": "JetBrains Mono",
        "color_scheme": "warm_light",
        "bg_base": "#faf9f7",
        "text_base": "#1c1a18",
        "accent_color": "#c45d35",
        "popularity": 85,
    },
    "cohere": {
        "name": "Cohere",
        "site": "Cohere",
        "category": "AI & ML",
        "description": "Vibrant gradients, data-rich dashboard aesthetic",
        "tags": ["ai", "data", "gradient", "technical"],
        "mood": "技术感强，数据丰富",
        "recommended_for": ["AI开发者", "数据科学家"],
        "font_primary": "Inter",
        "font_mono": "JetBrains Mono",
        "color_scheme": "dark_gradient",
        "bg_base": "#0a0a0f",
        "text_base": "#ffffff",
        "accent_color": "#5e60ce",
        "popularity": 65,
    },
    "ollama": {
        "name": "Ollama",
        "site": "Ollama",
        "category": "AI & ML",
        "description": "Terminal-first, monochrome simplicity",
        "tags": ["ai", "terminal", "minimal", "dark"],
        "mood": "极简终端风，技术硬核",
        "recommended_for": ["开发者", "AI极客"],
        "font_primary": "JetBrains Mono",
        "font_mono": "JetBrains Mono",
        "color_scheme": "dark_mono",
        "bg_base": "#1a1a1a",
        "text_base": "#e5e5e5",
        "accent_color": "#7c3aed",
        "popularity": 70,
    },
    "x.ai": {
        "name": "x.ai",
        "site": "xAI",
        "category": "AI & ML",
        "description": "Stark monochrome, futuristic minimalism, full monospace",
        "tags": ["ai", "futuristic", "monospace", "dark"],
        "mood": "未来感，极简高对比",
        "recommended_for": ["AI从业者", "技术先锋"],
        "font_primary": "JetBrains Mono",
        "font_mono": "JetBrains Mono",
        "color_scheme": "dark_mono",
        "bg_base": "#000000",
        "text_base": "#ffffff",
        "accent_color": "#ffffff",
        "popularity": 75,
    },
    "minimax": {
        "name": "MiniMax",
        "site": "MiniMax",
        "category": "AI & ML",
        "description": "Bold dark interface with neon accents",
        "tags": ["ai", "dark", "neon", "bold"],
        "mood": "大胆酷炫，视觉冲击强",
        "recommended_for": ["AI产品", "年轻用户"],
        "font_primary": "Inter",
        "font_mono": "JetBrains Mono",
        "color_scheme": "dark_neon",
        "bg_base": "#0d0d0d",
        "text_base": "#ffffff",
        "accent_color": "#00d4ff",
        "popularity": 60,
    },

    # ============================================================
    # Developer Tools & Platforms
    # ============================================================
    "linear.app": {
        "name": "Linear",
        "site": "Linear",
        "category": "Developer Tools",
        "description": "Ultra-minimal dark-mode, precise, purple accent",
        "tags": ["dark", "minimal", "developer", "product", "precise"],
        "mood": "冷静克制，结构极强",
        "recommended_for": ["开发者", "产品经理", "独立创作者"],
        "font_primary": "Inter",
        "font_mono": "JetBrains Mono",
        "color_scheme": "dark",
        "bg_base": "#08090a",
        "text_base": "#f7f8f8",
        "accent_color": "#7170ff",
        "popularity": 95,
    },
    "vercel": {
        "name": "Vercel",
        "site": "Vercel",
        "category": "Developer Tools",
        "description": "Black and white precision, Geist font system",
        "tags": ["dark", "minimal", "developer", "precise", "technical"],
        "mood": "极简技术感，高精度",
        "recommended_for": ["开发者", "技术产品", "SaaS"],
        "font_primary": "Geist",
        "font_mono": "Geist Mono",
        "color_scheme": "dark",
        "bg_base": "#000000",
        "text_base": "#ffffff",
        "accent_color": "#ffffff",
        "popularity": 90,
    },
    "raycast": {
        "name": "Raycast",
        "site": "Raycast",
        "category": "Developer Tools",
        "description": "Sleek dark chrome, vibrant gradient accents",
        "tags": ["dark", "gradient", "developer", "mac", "tool"],
        "mood": "现代感强，渐变点缀",
        "recommended_for": ["开发者", "效率工具用户"],
        "font_primary": "Inter",
        "font_mono": "JetBrains Mono",
        "color_scheme": "dark_gradient",
        "bg_base": "#0a0a0a",
        "text_base": "#ffffff",
        "accent_color": "#f5456e",
        "popularity": 82,
    },
    "supabase": {
        "name": "Supabase",
        "site": "Supabase",
        "category": "Developer Tools",
        "description": "Dark emerald theme, code-first developer tool",
        "tags": ["dark", "developer", "database", "green"],
        "mood": "技术硬核，翡翠绿点缀",
        "recommended_for": ["开发者", "后端工程师"],
        "font_primary": "Inter",
        "font_mono": "JetBrains Mono",
        "color_scheme": "dark",
        "bg_base": "#1a1a1a",
        "text_base": "#ffffff",
        "accent_color": "#3ecf8e",
        "popularity": 88,
    },
    "resend": {
        "name": "Resend",
        "site": "Resend",
        "category": "Developer Tools",
        "description": "Minimal dark theme, monospace accents",
        "tags": ["dark", "minimal", "developer", "email"],
        "mood": "极简克制，单色点缀",
        "recommended_for": ["开发者", "SaaS产品"],
        "font_primary": "Inter",
        "font_mono": "JetBrains Mono",
        "color_scheme": "dark",
        "bg_base": "#000000",
        "text_base": "#ffffff",
        "accent_color": "#ffffff",
        "popularity": 72,
    },
    "sentry": {
        "name": "Sentry",
        "site": "Sentry",
        "category": "Developer Tools",
        "description": "Dark dashboard, data-dense, pink-purple accent",
        "tags": ["dark", "dashboard", "developer", "data"],
        "mood": "数据密集，功能导向",
        "recommended_for": ["开发者", "DevOps"],
        "font_primary": "Rubik",
        "font_mono": "JetBrains Mono",
        "color_scheme": "dark",
        "bg_base": "#1a1a2e",
        "text_base": "#e5e5e5",
        "accent_color": "#e536ab",
        "popularity": 78,
    },
    "mintlify": {
        "name": "Mintlify",
        "site": "Mintlify",
        "category": "Developer Tools",
        "description": "Clean, green-accented, reading-optimized",
        "tags": ["light", "documentation", "developer", "clean"],
        "mood": "清新干净，阅读友好",
        "recommended_for": ["开发者", "技术文档"],
        "font_primary": "Inter",
        "font_mono": "JetBrains Mono",
        "color_scheme": "light",
        "bg_base": "#fafbfc",
        "text_base": "#1a1a1a",
        "accent_color": "#10b981",
        "popularity": 68,
    },
    "cursor": {
        "name": "Cursor",
        "site": "Cursor",
        "category": "Developer Tools",
        "description": "Sleek dark interface, gradient accents",
        "tags": ["dark", "gradient", "developer", "ai"],
        "mood": "现代AI感，渐变活力",
        "recommended_for": ["开发者", "AI工具用户"],
        "font_primary": "Inter",
        "font_mono": "JetBrains Mono",
        "color_scheme": "dark_gradient",
        "bg_base": "#0a0a0a",
        "text_base": "#ffffff",
        "accent_color": "#7c3aed",
        "popularity": 88,
    },

    # ============================================================
    # Design & Productivity
    # ============================================================
    "notion": {
        "name": "Notion",
        "site": "Notion",
        "category": "Design & Productivity",
        "description": "Warm minimalism, serif headings, soft surfaces",
        "tags": ["light", "warm", "minimal", "productivity", "soft"],
        "mood": "温暖纸质感，留白呼吸",
        "recommended_for": ["知识工作者", "创意人士", "个人品牌"],
        "font_primary": "Inter",
        "font_mono": "JetBrains Mono",
        "color_scheme": "warm_light",
        "bg_base": "#ffffff",
        "text_base": "rgba(0,0,0,0.95)",
        "accent_color": "#0075de",
        "popularity": 98,
    },
    "figma": {
        "name": "Figma",
        "site": "Figma",
        "category": "Design & Productivity",
        "description": "Vibrant multi-color, playful yet professional",
        "tags": ["light", "colorful", "design", "playful"],
        "mood": "活力多彩，专业有趣",
        "recommended_for": ["设计师", "创意人士"],
        "font_primary": "Inter",
        "font_mono": "Inter",
        "color_scheme": "colorful_light",
        "bg_base": "#ffffff",
        "text_base": "#000000",
        "accent_color": "#f24e1e",
        "popularity": 92,
    },
    "framer": {
        "name": "Framer",
        "site": "Framer",
        "category": "Design & Productivity",
        "description": "Bold black and blue, motion-first, design-forward",
        "tags": ["dark", "bold", "design", "motion"],
        "mood": "大胆冲击力，设计感强",
        "recommended_for": ["设计师", "创意总监", "品牌展示"],
        "font_primary": "Inter",
        "font_mono": "JetBrains Mono",
        "color_scheme": "bold_dark",
        "bg_base": "#0a0a0a",
        "text_base": "#ffffff",
        "accent_color": "#0055ff",
        "popularity": 86,
    },
    "cal.com": {
        "name": "Cal.com",
        "site": "Cal.com",
        "category": "Design & Productivity",
        "description": "Clean neutral UI, developer-oriented simplicity",
        "tags": ["light", "minimal", "developer", "calendar"],
        "mood": "干净中性，功能简洁",
        "recommended_for": ["开发者", "个人品牌"],
        "font_primary": "Inter",
        "font_mono": "Inter",
        "color_scheme": "light",
        "bg_base": "#ffffff",
        "text_base": "#1a1a1a",
        "accent_color": "#666666",
        "popularity": 65,
    },
    "miro": {
        "name": "Miro",
        "site": "Miro",
        "category": "Design & Productivity",
        "description": "Bright yellow accent, infinite canvas aesthetic",
        "tags": ["light", "yellow", "collaboration", "creative"],
        "mood": "明亮活泼，协作感",
        "recommended_for": ["创意人士", "团队协作"],
        "font_primary": "Inter",
        "font_mono": "Inter",
        "color_scheme": "light",
        "bg_base": "#ffffff",
        "text_base": "#1a1a1a",
        "accent_color": "#ffd02f",
        "popularity": 80,
    },
    "airtable": {
        "name": "Airtable",
        "site": "Airtable",
        "category": "Design & Productivity",
        "description": "Colorful, friendly, structured data aesthetic",
        "tags": ["light", "colorful", "productivity", "data"],
        "mood": "友好多彩，结构清晰",
        "recommended_for": ["产品经理", "数据工作者"],
        "font_primary": "Inter",
        "font_mono": "Inter",
        "color_scheme": "colorful_light",
        "bg_base": "#ffffff",
        "text_base": "#1a1a1a",
        "accent_color": "#f8a5c2",
        "popularity": 78,
    },

    # ============================================================
    # Marketing & Landing
    # ============================================================
    "stripe": {
        "name": "Stripe",
        "site": "Stripe",
        "category": "Fintech",
        "description": "Signature purple gradients, weight-300 elegance",
        "tags": ["light", "fintech", "premium", "gradient"],
        "mood": "金融精致，高端克制",
        "recommended_for": ["金融从业者", "B2B SaaS", "独立开发者"],
        "font_primary": "Source Sans 3",
        "font_mono": "Source Code Pro",
        "color_scheme": "light",
        "bg_base": "#ffffff",
        "text_base": "#061b31",
        "accent_color": "#533afd",
        "popularity": 96,
    },
    "apple": {
        "name": "Apple",
        "site": "Apple",
        "category": "Enterprise & Consumer",
        "description": "Premium white space, SF Pro, cinematic imagery",
        "tags": ["light", "premium", "minimal", "cinematic"],
        "mood": "极致高端，纯净大气",
        "recommended_for": ["高端品牌", "科技产品", "设计作品集"],
        "font_primary": "SF Pro",
        "font_mono": "SF Mono",
        "color_scheme": "premium_light",
        "bg_base": "#ffffff",
        "text_base": "#1d1d1f",
        "accent_color": "#0071e3",
        "popularity": 99,
    },
    "airbnb": {
        "name": "Airbnb",
        "site": "Airbnb",
        "category": "Enterprise & Consumer",
        "description": "Warm coral accent, photography-driven, rounded UI",
        "tags": ["light", "warm", "photography", "rounded"],
        "mood": "温暖亲切，摄影主导",
        "recommended_for": ["旅行/生活方式创作者", "民宿/体验类"],
        "font_primary": "DM Sans",
        "font_mono": "DM Mono",
        "color_scheme": "warm_light",
        "bg_base": "#ffffff",
        "text_base": "#222222",
        "accent_color": "#ff5a5f",
        "popularity": 90,
    },
    "spotify": {
        "name": "Spotify",
        "site": "Spotify",
        "category": "Enterprise & Consumer",
        "description": "Vibrant green on dark, bold type, album-art-driven",
        "tags": ["dark", "bold", "music", "branded"],
        "mood": "音乐感强，视觉大胆",
        "recommended_for": ["音乐人", "播客主", "内容创作者"],
        "font_primary": "DM Sans",
        "font_mono": "DM Mono",
        "color_scheme": "dark",
        "bg_base": "#121212",
        "text_base": "#ffffff",
        "accent_color": "#1db954",
        "popularity": 88,
    },
    "spacex": {
        "name": "SpaceX",
        "site": "SpaceX",
        "category": "Enterprise & Consumer",
        "description": "Stark black and white, full-bleed imagery, futuristic",
        "tags": ["dark", "bold", "space", "futuristic"],
        "mood": "太空感，极简高对比",
        "recommended_for": ["科技创始人", "硬核技术品牌"],
        "font_primary": "Inter",
        "font_mono": "JetBrains Mono",
        "color_scheme": "stark_dark",
        "bg_base": "#000000",
        "text_base": "#ffffff",
        "accent_color": "#ffffff",
        "popularity": 75,
    },
    "revolut": {
        "name": "Revolut",
        "site": "Revolut",
        "category": "Fintech",
        "description": "Sleek dark interface, gradient cards, fintech precision",
        "tags": ["dark", "fintech", "gradient", "premium"],
        "mood": "金融科技感，精致深色",
        "recommended_for": ["金融科技", "支付产品"],
        "font_primary": "DM Sans",
        "font_mono": "DM Mono",
        "color_scheme": "dark_gradient",
        "bg_base": "#0a0a0a",
        "text_base": "#ffffff",
        "accent_color": "#1e3a5f",
        "popularity": 78,
    },

    # ============================================================
    # Documentation & Knowledge
    # ============================================================
    "sanity": {
        "name": "Sanity",
        "site": "Sanity",
        "category": "Documentation & Knowledge",
        "description": "Red accent, content-first editorial layout",
        "tags": ["light", "editorial", "documentation", "content"],
        "mood": "编辑感强，内容优先",
        "recommended_for": ["内容创作者", "写作者", "媒体"],
        "font_primary": "Space Grotesk",
        "font_mono": "JetBrains Mono",
        "color_scheme": "editorial_light",
        "bg_base": "#ffffff",
        "text_base": "#1a1a1a",
        "accent_color": "#e63946",
        "popularity": 72,
    },
    "mongodb": {
        "name": "MongoDB",
        "site": "MongoDB",
        "category": "Documentation & Knowledge",
        "description": "Green leaf branding, developer documentation focus",
        "tags": ["light", "developer", "documentation", "green"],
        "mood": "清新技术感，文档友好",
        "recommended_for": ["开发者", "技术文档"],
        "font_primary": "Inter",
        "font_mono": "JetBrains Mono",
        "color_scheme": "light",
        "bg_base": "#ffffff",
        "text_base": "#1a1a1a",
        "accent_color": "#00ed64",
        "popularity": 80,
    },
    "hashicorp": {
        "name": "HashiCorp",
        "site": "HashiCorp",
        "category": "Infrastructure & Cloud",
        "description": "Enterprise-clean, black and white",
        "tags": ["dark", "enterprise", "technical", "minimal"],
        "mood": "企业技术感，简洁权威",
        "recommended_for": ["企业服务", "DevOps", "云基础设施"],
        "font_primary": "Inter",
        "font_mono": "JetBrains Mono",
        "color_scheme": "dark",
        "bg_base": "#000000",
        "text_base": "#ffffff",
        "accent_color": "#60dea9",
        "popularity": 70,
    },
    "clickhouse": {
        "name": "ClickHouse",
        "site": "ClickHouse",
        "category": "Infrastructure & Cloud",
        "description": "Yellow-accented, technical documentation style",
        "tags": ["dark", "data", "technical", "yellow"],
        "mood": "数据密集，黄色活力",
        "recommended_for": ["数据工程师", "技术文档"],
        "font_primary": "Inter",
        "font_mono": "JetBrains Mono",
        "color_scheme": "dark",
        "bg_base": "#1a1a1a",
        "text_base": "#ffffff",
        "accent_color": "#ffcc00",
        "popularity": 65,
    },
}


def get_design_system(name: str) -> dict:
    """Get design system by name. Returns None if not found."""
    return DESIGN_SYSTEMS.get(name)


def list_design_systems(category: str = None, tags: list = None) -> list:
    """
    List design systems, optionally filtered by category or tags.
    
    Args:
        category: Filter by category (e.g. "Developer Tools", "Design & Productivity")
        tags: List of tags, returns systems matching ANY tag
    
    Returns:
        List of (name, system_dict) tuples
    """
    results = []
    for name, system in DESIGN_SYSTEMS.items():
        if category and system.get("category") != category:
            continue
        if tags:
            system_tags = set(system.get("tags", []))
            if not system_tags.intersection(tags):
                continue
        results.append((name, system))
    return results


def get_categories() -> list:
    """Get all unique categories."""
    return sorted(set(s.get("category") for s in DESIGN_SYSTEMS.values()))


def get_all_tags() -> list:
    """Get all unique tags across design systems."""
    tags = set()
    for s in DESIGN_SYSTEMS.values():
        tags.update(s.get("tags", []))
    return sorted(tags)
