'use client';

import { useEffect, useMemo, useRef, useState, useCallback } from 'react';
import React from 'react';
import styles from './page.module.css';
import mammoth from 'mammoth';

let pdfjsModule: typeof import('pdfjs-dist') | null = null;

async function getPdfjsModule() {
  if (pdfjsModule) return pdfjsModule;

  const module = await import('pdfjs-dist');
  module.GlobalWorkerOptions.workerSrc = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${module.version}/build/pdf.worker.min.mjs`;
  pdfjsModule = module;
  return module;
}

interface Dimension {
  icon: string;
  label: string;
  score: number;
  text: string;
}

interface ProfileData {
  name: string;
  role: string;
  company: string;
  skills: string[];
  education: string[];
  projects: string[];
  achievements: string[];
  values: string[];
  direction: string[];
  summary: string;
}

interface AnalysisResult {
  dimensions: Dimension[];
  short_story: string;
  full_story: string;
  mbti: string;
  profile?: ProfileData;
}

interface DesignSystem {
  id: string;
  name: string;
  category: string;
  description: string;
  mood: string;
  recommended_for: string[];
  font_primary: string;
  preview?: { bg: string; text: string; accent: string };
  popularity: number;
}

const STATUS_LABELS = [
  '正在识别关键信息…',
  '蒸馏职业维度…',
  '提取核心技能…',
  '分析项目成就…',
  '梳理教育背景…',
  '洞察行业视野…',
  '刻画个人特质…',
  '评估发展潜力…',
  '生成叙事文本…',
];

const DIM_ICONS: Record<string, string> = {
  i1: '◎',
  i2: '◈',
  i3: '◉',
  i4: '△',
  i5: '◇',
  i6: '□',
  i7: '○',
};

const DEFAULT_PREVIEW_HTML = `<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
      body {
        margin: 0;
        font-family: Inter, Arial, sans-serif;
        background: #0c0c0f;
        color: #f0ede8;
        min-height: 100vh;
        display: grid;
        place-items: center;
      }
      .card {
        max-width: 720px;
        padding: 36px 30px;
        border-radius: 20px;
        background: rgba(24, 24, 28, 0.98);
        border: 1px solid rgba(255, 255, 255, 0.08);
        text-align: center;
      }
      h1 { font-size: 30px; margin-bottom: 12px; }
      p { color: #9a958e; line-height: 1.8; }
    </style>
  </head>
  <body>
    <div class="card">
      <h1>预览区域</h1>
      <p>完成生成后，这里会展示你的网站预览效果，便于直接确认最终的展示样式。</p>
    </div>
  </body>
</html>`;

function normalizeExtractedText(text: string) {
  return text
    .replace(/\u0000/g, '')
    .replace(/\r/g, '')
    .replace(/[ \t]+/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function sanitizeResumeText(text: string) {
  const original = normalizeExtractedText(text);
  if (!original) return '';

  const cleanedLines = original
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .filter((line) => {
      if (/^(page|pagenumber|pdf|docx|doc|word|generated by|created by|copyright|©|all rights reserved)/i.test(line)) {
        return false;
      }
      if (/^(https?:\/\/|www\.)/i.test(line)) {
        return false;
      }
      const letters = line.replace(/[^A-Za-z\u4e00-\u9fa5]/g, '');
      if (letters.length < 2 && line.length > 18) {
        return false;
      }
      const symbolRatio = (line.match(/[^A-Za-z0-9\u4e00-\u9fa5\s]/g) || []).length / Math.max(line.length, 1);
      if (symbolRatio > 0.45 && line.length > 12) {
        return false;
      }
      return true;
    });

  const deduped = Array.from(new Set(cleanedLines));
  const cleaned = deduped.join('\n').replace(/\n{3,}/g, '\n\n').trim();

  return cleaned.length >= 30 ? cleaned : original;
}

function splitSentences(text: string) {
  return text
    .split(/[。！？!?\n]+/)
    .map((item) => item.trim())
    .filter(Boolean);
}

function extractName(text: string, lines: string[]) {
  const firstLine = lines[0] || '';
  if (firstLine.includes('|')) {
    return firstLine.split('|')[0].trim();
  }

  const candidate = firstLine.match(/^[A-Za-z\u4e00-\u9fa5·\s]{2,20}$/);
  if (candidate) {
    return candidate[0].trim();
  }

  return '我';
}

function extractRole(text: string) {
  const roleMatch = text.match(/(高级前端工程师|前端工程师|全栈工程师|产品经理|产品设计师|设计师|运营经理|市场经理|数据分析师|研发工程师|技术负责人|创始人|工程师|产品|运营|设计|开发|研究)/);
  if (roleMatch) return roleMatch[1];
  return '创作者';
}

function extractCompany(text: string) {
  const companyMatch = text.match(/([A-Za-z0-9\u4e00-\u9fa5·\-]+(?:科技|集团|公司|实验室|团队|平台|工作室|有限公司))/);
  return companyMatch?.[1] || '';
}

function extractSkills(text: string) {
  const candidates = [
    'TypeScript',
    'JavaScript',
    'React',
    'Next.js',
    'Node.js',
    'Python',
    'SQL',
    'AI',
    '产品',
    '数据分析',
    '架构',
    '设计',
    'UX',
    'UI',
    'Figma',
    '增长',
    '运营',
    '用户体验',
  ];

  return candidates.filter((item) => text.includes(item)).slice(0, 8);
}

function extractEducation(lines: string[]) {
  return lines.filter((line) => /(大学|学校|本科|硕士|博士|学历|教育)/.test(line)).slice(0, 2);
}

function extractProjects(text: string) {
  return splitSentences(text)
    .filter((sentence) => /(项目|主导|负责|落地|上线|优化|迭代|搭建|重构|交付|设计|开发|推动|实现)/.test(sentence))
    .slice(0, 3);
}

function extractAchievements(text: string) {
  return splitSentences(text)
    .filter((sentence) => /(\d+%|百分之|增长|提升|降低|覆盖|获|荣获|发布|完成|达成|拿下|斩获|显著)/.test(sentence))
    .slice(0, 3);
}

function inferMbti(text: string, role: string) {
  const lowerText = text.toLowerCase();
  if (/(沟通|客户|市场|运营|销售|产品)/.test(lowerText)) return 'ENFP';
  if (/(数据|架构|系统|工程|技术|算法|分析|前端|后端|研发)/.test(lowerText)) return 'INTJ';
  if (/(设计|创意|体验|用户|视觉|ui|ux)/.test(lowerText)) return 'INFP';
  if (/(管理|执行|领导|目标|结果|运营|增长)/.test(lowerText)) return 'ESTJ';
  if (role.includes('设计') || role.includes('产品')) return 'ENFP';
  return 'INTJ';
}

function buildProfileData(resumeText: string, analysis?: AnalysisResult | null): ProfileData {
  const normalized = normalizeExtractedText(resumeText);
  const lines = normalized
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);
  const text = normalized.replace(/\s+/g, ' ');

  const name = extractName(text, lines);
  const role = extractRole(text);
  const company = extractCompany(text);
  const skillsFromText = extractSkills(text);
  const educationLines = extractEducation(lines);
  const projects = extractProjects(text);
  const achievements = extractAchievements(text);

  const skillSource = analysis?.dimensions.find((dim) => dim.label.includes('技能') || dim.label.includes('核心'))?.text || '';
  const parsedSkills = skillSource
    .split(/[，、,\n]/)
    .map((item) => item.trim())
    .filter(Boolean)
    .slice(0, 8);

  const skills = skillsFromText.length > 0 ? skillsFromText : parsedSkills;
  const summary = analysis?.short_story || [role, company, projects[0]].filter(Boolean).join(' · ');

  return {
    name,
    role,
    company,
    skills,
    education: educationLines,
    projects,
    achievements,
    values: /用户|价值|成长|原则|诚信|目标/.test(text)
      ? ['目标感', '成长意识', '价值判断']
      : ['执行力', '目标意识', '可持续思维'],
    direction: /产品|运营|增长|市场|数据|架构|系统|技术|AI/.test(text)
      ? ['产品增长', '技术架构', '数据能力']
      : ['职业深耕', '能力扩展'],
    summary,
  };
}

function createFallbackAnalysis(resumeText: string): AnalysisResult {
  const normalized = normalizeExtractedText(resumeText);
  const lines = normalized
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);
  const text = normalized.replace(/\s+/g, ' ');

  const name = extractName(text, lines);
  const role = extractRole(text);
  const company = extractCompany(text);
  const skills = extractSkills(text);
  const educationLines = extractEducation(lines);
  const projects = extractProjects(text);
  const achievements = extractAchievements(text);

  const skillText = skills.length > 0 ? skills.join('、') : '专业能力与方法论';
  const educationText = educationLines.length > 0 ? educationLines.join('；') : '教育背景信息较为简略。';
  const projectText = projects.length > 0 ? projects.join('；') : '项目经验在简历中有体现。';
  const achievementText = achievements.length > 0 ? achievements.join('；') : '亮点表现出较强的执行力与成果导向。';

  const shortStory = [role, company, projectText].filter(Boolean).join(' · ').slice(0, 110);
  const fullStory = [
    `${name} 是一位${role}${company ? `，目前在${company}` : ''}的从业者。`,
    projectText,
    achievementText,
  ]
    .filter(Boolean)
    .join(' ')
    .slice(0, 260);

  const mbti = inferMbti(text, role);

  return {
    dimensions: [
      {
        icon: '💼',
        label: '职业经历',
        score: 62 + Math.min(25, Math.floor(text.length / 160)),
        text: `${role}${company ? `，当前就职于 ${company}` : ''}。${projects[0] || '职业轨迹清晰，具备长期积累。'} `,
      },
      {
        icon: '🧠',
        label: '核心技能',
        score: 58 + Math.min(28, skills.length * 8),
        text: `核心能力聚焦在 ${skillText}。`,
      },
      {
        icon: '🎓',
        label: '教育背景',
        score: 55 + (educationLines.length > 0 ? 20 : 0),
        text: educationText,
      },
      {
        icon: '💡',
        label: '项目经验',
        score: 60 + Math.min(25, projects.length * 10),
        text: projectText,
      },
      {
        icon: '🌟',
        label: '成就亮点',
        score: 56 + Math.min(24, achievements.length * 10),
        text: achievementText,
      },
      {
        icon: '🔍',
        label: '洞察与价值观',
        score: 58,
        text: /用户|价值|成长|原则|诚信|目标/.test(text)
          ? '简历中体现出明确的价值判断与持续成长意识。'
          : '整体呈现出较强的目标感、执行力和可持续成长思维。',
      },
      {
        icon: '⚡',
        label: '潜力与方向',
        score: 57,
        text: /产品|运营|增长|市场|数据|架构|系统|技术|AI/.test(text)
          ? '未来可在产品、增长、技术与数据方向继续深化。'
          : '未来有较好的扩展空间，适合持续打磨核心能力与影响力。',
      },
    ],
    short_story: shortStory,
    full_story: fullStory,
    mbti,
    profile: buildProfileData(resumeText, {
      dimensions: [
        {
          icon: '💼',
          label: '职业经历',
          score: 0,
          text: `${role}${company ? `，当前就职于 ${company}` : ''}。${projects[0] || '职业轨迹清晰，具备长期积累。'} `,
        },
        {
          icon: '🧠',
          label: '核心技能',
          score: 0,
          text: `核心能力聚焦在 ${skillText}。`,
        },
        {
          icon: '🎓',
          label: '教育背景',
          score: 0,
          text: educationText,
        },
        {
          icon: '💡',
          label: '项目经验',
          score: 0,
          text: projectText,
        },
        {
          icon: '🌟',
          label: '成就亮点',
          score: 0,
          text: achievementText,
        },
        {
          icon: '🔍',
          label: '洞察与价值观',
          score: 0,
          text: '',
        },
        {
          icon: '⚡',
          label: '潜力与方向',
          score: 0,
          text: '',
        },
      ],
      short_story: shortStory,
      full_story: fullStory,
      mbti,
    }),
  };
}

export default function GeneratePage() {
  const [activeStep, setActiveStep] = useState(1);
  const [resumeText, setResumeText] = useState('');
  const [fileName, setFileName] = useState('');
  const [isExtracting, setIsExtracting] = useState(false);
  const [analysisResult, setAnalysisResult] = useState<AnalysisResult | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analyzeIdx, setAnalyzeIdx] = useState(0);
  const [isGenerating, setIsGenerating] = useState(false);
  const [designSystems, setDesignSystems] = useState<DesignSystem[]>([]);
  const [selectedStyle, setSelectedStyle] = useState<string | null>(null);
  const [generatedHtml, setGeneratedHtml] = useState('');
  const [toastMsg, setToastMsg] = useState('');
  const [toastVisible, setToastVisible] = useState(false);
  const [touchStartX, setTouchStartX] = useState<number | null>(null);
  const [selectedTemplate, setSelectedTemplate] = useState<string>('developerfolio');
  const fileInputRef = useRef<HTMLInputElement>(null);
  // Editable fields for Step 2 (7 IP dimensions + narratives)

  useEffect(() => {
    fetch('/api/designs')
      .then((r) => r.json())
      .then((data) => setDesignSystems(data.designs || []))
      .catch(() => undefined);
  }, []);

  useEffect(() => {
    if (!toastVisible) return;
    const timer = window.setTimeout(() => setToastVisible(false), 2500);
    return () => window.clearTimeout(timer);
  }, [toastVisible]);

  const showToast = useCallback((msg: string) => {
    setToastMsg(msg);
    setToastVisible(true);
  }, []);

  const goToStep = useCallback(
    (nextStep: number) => {
      if (nextStep < 1 || nextStep > 4) return;
      if (nextStep === 2 && !resumeText.trim()) {
        showToast('请先上传文件或粘贴简历文本');
        return;
      }
      if (nextStep === 3 && !analysisResult) {
        showToast('请先完成 AI 解析');
        return;
      }
      if (nextStep === 4 && !selectedStyle) {
        showToast('请先选择一套视觉风格');
        return;
      }
      setActiveStep(nextStep);
    },
    [analysisResult, resumeText, selectedStyle, showToast]
  );

  const runAnalysis = useCallback(async () => {
    if (isAnalyzing) return;

    const cleanedResumeText = sanitizeResumeText(resumeText);
    if (!cleanedResumeText.trim()) {
      showToast('请先上传文件或粘贴简历文本');
      return;
    }

    if (cleanedResumeText !== resumeText) {
      setResumeText(cleanedResumeText);
    }

    setIsAnalyzing(true);
    setAnalyzeIdx(0);

    let idx = 0;
    const interval = window.setInterval(() => {
      idx = Math.min(idx + 1, STATUS_LABELS.length - 1);
      setAnalyzeIdx(idx);
    }, 380);

    try {
      const res = await fetch('/api/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ resume_text: cleanedResumeText }),
      });

      if (!res.ok) throw new Error('Analysis failed');
      const data = await res.json();
      clearInterval(interval);
      setAnalysisResult({
        ...data,
        profile: buildProfileData(cleanedResumeText, data),
      });
      setActiveStep(3);
    } catch {
      clearInterval(interval);
      showToast('解析失败，请重试');
    } finally {
      setIsAnalyzing(false);
    }
  }, [isAnalyzing, resumeText, showToast]);

  const handleAnalyze = useCallback(() => {
    if (!resumeText.trim()) {
      showToast('请先上传文件或粘贴简历文本');
      return;
    }
    runAnalysis();
  }, [resumeText, runAnalysis, showToast]);

  const handleGenerate = useCallback(async () => {
    if (!selectedStyle) {
      showToast('请先选择一套视觉风格');
      return;
    }

    if (!analysisResult) {
      showToast('请先完成 AI 解析');
      return;
    }

    const profile = analysisResult.profile ?? buildProfileData(resumeText, analysisResult);

    setIsGenerating(true);

    // 添加 30 秒超时控制
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 30000);

    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          dimensions: analysisResult.dimensions,
          short_story: analysisResult.short_story,
          full_story: analysisResult.full_story,
          mbti: analysisResult.mbti,
          style: selectedStyle,
          template: selectedTemplate,
          profile,
        }),
        signal: controller.signal,
      });
      
      clearTimeout(timeoutId);

      if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        throw new Error(errorData.error || errorData.details || 'Generation failed');
      }
      
      const data = await res.json();
      
      if (!data.html || data.html.length < 100) {
        throw new Error('生成的 HTML 内容过短，可能生成失败');
      }
      
      setGeneratedHtml(data.html);
      setActiveStep(4);
      showToast('页面已生成，预览和下载已经就绪');
    } catch (error) {
      clearTimeout(timeoutId);
      
      let errorMsg = '生成失败，请重试';
      if (error instanceof Error) {
        if (error.name === 'AbortError') {
          errorMsg = '生成超时（30 秒），请检查网络后重试';
        } else {
          errorMsg = error.message;
        }
      }
      console.error('Generation error:', error);
      showToast(`生成失败：${errorMsg}`);
    } finally {
      setIsGenerating(false);
    }
  }, [analysisResult, selectedStyle, resumeText, showToast]);

  const handleFileChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (!file) return;

      const ext = file.name.split('.').pop()?.toLowerCase() || '';
      if (!['pdf', 'docx', 'doc'].includes(ext)) {
        showToast('仅支持 PDF / DOCX / DOC 格式');
        return;
      }

      setFileName(file.name);
      setIsExtracting(true);

      const reader = new FileReader();
      reader.onload = async (event) => {
        try {
          const arrayBuffer = event.target?.result as ArrayBuffer;
          let text = '';

          if (ext === 'pdf') {
            const pdfjsLib = await getPdfjsModule();
            const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;
            const pageTexts: string[] = [];

            for (let i = 1; i <= pdf.numPages; i += 1) {
              const page = await pdf.getPage(i);
              const content = await page.getTextContent({ includeMarkedContent: false });
              const pageText = content.items
                .map((item: any) => (typeof item?.str === 'string' ? item.str : ''))
                .join(' ')
                .replace(/\s+/g, ' ')
                .trim();
              pageTexts.push(pageText);
            }

            text = pageTexts.join('\n\n');
          } else {
            const result = await mammoth.extractRawText({ arrayBuffer });
            text = result.value;
          }

          const normalized = sanitizeResumeText(text);
          if (!normalized || normalized.length < 20) {
            showToast('未识别到可用文本，请改用粘贴输入或者更换文件');
            return;
          }

          setResumeText(normalized);
          showToast(ext === 'pdf' ? 'PDF 文本已提取' : '文档文本已提取');
        } catch {
          showToast('文件读取失败，请尝试粘贴文本');
        } finally {
          setIsExtracting(false);
        }
      };

      reader.onerror = () => {
        setIsExtracting(false);
        showToast('文件读取失败');
      };

      reader.readAsArrayBuffer(file);
    },
    [showToast]
  );

  const selectedDesign = useMemo(() => designSystems.find((item) => item.id === selectedStyle) || null, [designSystems, selectedStyle]);
  const profile = useMemo(() => analysisResult?.profile ?? buildProfileData(resumeText, analysisResult), [analysisResult, resumeText]);
  const previewDoc = generatedHtml || DEFAULT_PREVIEW_HTML;

  const handleTouchStart = useCallback((event: React.TouchEvent<HTMLDivElement>) => {
    setTouchStartX(event.touches[0]?.clientX ?? null);
  }, []);

  const handleTouchEnd = useCallback(
    (event: React.TouchEvent<HTMLDivElement>) => {
      if (touchStartX === null) return;
      const diff = (event.changedTouches[0]?.clientX ?? 0) - touchStartX;
      if (Math.abs(diff) < 50) return;

      if (diff > 0 && activeStep > 1) {
        goToStep(activeStep - 1);
      } else if (diff < 0 && activeStep < 4) {
        goToStep(activeStep + 1);
      }
      setTouchStartX(null);
    },
    [activeStep, goToStep, touchStartX]
  );

  return (
    <div className={styles.page}>
      <nav className={styles.nav} role="navigation" aria-label="生成流程导航">
        <div className={styles.navContainer}>
          <div className={styles.navLogo}>
            <a href="/" aria-label="返回首页">Personal <strong style={{ color: 'var(--accent)' }}>IP</strong> Site · 生成器</a>
          </div>
          <div className={styles.navHint} role="status" aria-live="polite">Step {activeStep} / 4</div>
        </div>
      </nav>

      <div className={styles.stepperSection}>
        <div className={styles.navContainer}>
          <div className={styles.stepper}>
            {[1, 2, 3, 4].map((step) => (
              <React.Fragment key={step}>
                <button
                  type="button"
                  className={`${styles.stepItem} ${activeStep === step ? styles.active : ''} ${activeStep > step ? styles.done : ''}`}
                  onClick={() => goToStep(step)}
                  aria-current={activeStep === step ? 'step' : undefined}
                  aria-label={`步骤 ${step}: ${['上传简历', 'AI 解析', '选择风格', '下载使用'][step - 1]}`}
                >
                  <span className={styles.stepCircle} aria-hidden="true">{activeStep > step ? '✓' : step}</span>
                  <span className={styles.stepLabel}>{['上传简历', 'AI 解析', '选择风格', '下载使用'][step - 1]}</span>
                </button>
                {step < 4 && <span className={`${styles.stepArrow} ${activeStep > step ? styles.filled : ''}`}>→</span>}
              </React.Fragment>
            ))}
          </div>
        </div>
      </div>

      <div className={styles.sliderShell} onTouchStart={handleTouchStart} onTouchEnd={handleTouchEnd}>
        <div className={styles.sliderTrack} style={{ transform: `translateX(-${(activeStep - 1) * 100}%)` }}>
          <section className={styles.stepSlide}>
            <div className={styles.container}>
              <p className={styles.sectionLabel}>STEP 1</p>
              <h2 className={styles.sectionTitle}>上传简历</h2>
              <p className={styles.sectionSubtitle}>
                上传 PDF 或 Word 文件，或者直接粘贴简历文本。系统会优先提取文本内容，再进入叙事生成流程。
              </p>

              <div className={styles.uploadZone} onClick={() => fileInputRef.current?.click()} role="button" tabIndex={0} aria-label="上传简历文件">
                <div className={styles.uploadIcon} aria-hidden="true">{isExtracting ? '⏳' : '↗'}</div>
                <div className={styles.uploadTitle}>{isExtracting ? '正在提取文本…' : '点击上传文件'}</div>
                <div className={styles.uploadHint}>支持 PDF / DOCX / DOC，不超过 10MB</div>
                <div className={styles.uploadFormats}>
                  <span className={styles.formatBadge}>.pdf</span>
                  <span className={styles.formatBadge}>.docx</span>
                  <span className={styles.formatBadge}>.doc</span>
                </div>
              </div>

              <input
                ref={fileInputRef}
                type="file"
                accept=".pdf,.docx,.doc"
                style={{ display: 'none' }}
                onChange={handleFileChange}
                aria-label="选择简历文件"
              />

              {fileName && (
                <div className={styles.fileCard}>
                  <div className={styles.fileIconBadge}>{fileName.split('.').pop()?.toUpperCase()}</div>
                  <div>
                    <div className={styles.fileName}>{fileName}</div>
                  </div>
                  <button type="button" className={styles.fileRemove} onClick={() => { setFileName(''); setResumeText(''); }}>
                    ×
                  </button>
                </div>
              )}

              <div className={styles.uploadOr}>或者直接粘贴文本</div>

              <textarea
                className={styles.pasteBox}
                value={resumeText}
                onChange={(event) => setResumeText(event.target.value)}
                placeholder={`在此粘贴你的简历全文……\n\n示例：\n张三 | 高级前端工程师\n2019 — 2024  ABC 科技  前端技术负责人\n主导设计并落地了公司级组件库，覆盖 12 条业务线……`}
                aria-label="粘贴简历文本"
                aria-describedby="paste-hint"
              />
              <div id="paste-hint" className="sr-only" style={{ position: 'absolute', width: '1px', height: '1px', overflow: 'hidden' }}>
                在此粘贴你的简历全文，包括工作经历、项目经验、技能等信息
              </div>

              <div className={styles.stepActions}>
                <button type="button" className={`${styles.btn} ${styles.btnPrimary} ${styles.btnWide}`} onClick={handleAnalyze} aria-label="开始 AI 解析简历">
                  开始 AI 解析 →
                </button>
              </div>
            </div>
          </section>

          <section className={styles.stepSlide}>
            <div className={styles.container}>
              <p className={styles.sectionLabel}>STEP 2</p>
              <h2 className={styles.sectionTitle}>AI 智能解析</h2>
              <p className={styles.sectionSubtitle}>
                解析结果会基于你的简历关键词生成更有画面感的叙事内容，并自动推进到风格选择步骤。
              </p>

              {!analysisResult ? (
                <div className={styles.analysisStatus}>
                  <div className={styles.pulse} />
                  <div className={styles.dots}>
                    <span />
                    <span />
                    <span />
                  </div>
                  <div className={styles.statusText}>{STATUS_LABELS[Math.min(analyzeIdx, STATUS_LABELS.length - 1)]}</div>
                </div>
              ) : (
                <div className={styles.dimensionsGrid}>
                  {analysisResult.dimensions.map((dim, index) => (
                    <div key={dim.label} className={styles.dimCard}>
                      <div className={styles.dimHeader}>
                        <div className={`${styles.dimIcon} ${styles[`i${index + 1}` as keyof typeof styles]}`}>{DIM_ICONS[`i${index + 1}`]}</div>
                        <div className={styles.dimLabel}>{dim.label}</div>
                        <div className={styles.dimScore}>{dim.score}</div>
                      </div>
                      <div className={styles.dimText}>{dim.text}</div>
                    </div>
                  ))}
                </div>
              )}

              <div className={styles.stepActions}>
                <button type="button" className={`${styles.btn} ${styles.btnSecondary}`} onClick={() => goToStep(1)}>
                  ← 返回上传
                </button>
                <button type="button" className={`${styles.btn} ${styles.btnPrimary}`} onClick={() => goToStep(3)}>
                  选择视觉风格 →
                </button>
              </div>
            </div>
          </section>

          <section className={styles.stepSlide}>
            <div className={styles.container}>
              <p className={styles.sectionLabel}>STEP 3</p>
              <h2 className={styles.sectionTitle}>选择视觉风格</h2>
              <p className={styles.sectionSubtitle}>
                从 31 套设计系统中选择适合你的风格，生成页面会即时跟随切换。
              </p>

              <div className={styles.stylesGrid}>
                {designSystems.map((style) => (
                  <button
                    key={style.id}
                    type="button"
                    className={`${styles.styleCard} ${selectedStyle === style.id ? styles.selected : ''}`}
                    onClick={() => setSelectedStyle(style.id)}
                  >
                    <div
                      className={styles.styleThumb}
                      style={{
                        background: style.preview?.bg || '#111114',
                        color: style.preview?.text || '#f0ede8',
                      }}
                    >
                      <span className={styles.styleThumbBadge}>{style.category}</span>
                      <div className={styles.styleThumbBottom}>
                        <span className={styles.styleThumbTitle}>{style.name}</span>
                        <span className={styles.styleThumbMood}>{style.mood || style.description}</span>
                      </div>
                      <span className={styles.styleAccentLine} style={{ background: style.preview?.accent || 'var(--accent)' }} />
                    </div>
                    <div className={styles.styleMeta}>
                      <div className={styles.styleTitle}>{style.name}</div>
                      <div className={styles.styleDescription}>{style.description}</div>
                    </div>
                    <div className={styles.styleCheck}>✓</div>
                  </button>
                ))}
              </div>

              <div className={styles.previewFrame}>
                <div className={styles.previewBar}>
                  <div className={styles.previewDots}>
                    <span />
                    <span />
                    <span />
                  </div>
                  <div className={styles.previewUrl}>{selectedDesign?.name || '选择一种风格后，预览信息会实时更新'}</div>
                </div>
                <div
                  className={styles.previewBody}
                  style={{
                    background: selectedDesign?.preview?.bg || '#0c0c0f',
                    color: selectedDesign?.preview?.text || '#f0ede8',
                    borderTop: `3px solid ${selectedDesign?.preview?.accent || 'var(--accent)'}`,
                  }}
                >
                  <div className={styles.previewContent}>
                    <div className={styles.previewMetaRow}>
                      <span className={styles.previewPill}>{selectedDesign?.category || '视觉风格'}</span>
                      <span className={styles.previewPill}>{selectedDesign?.mood || '气质待定'}</span>
                    </div>
                    <p className={styles.previewEyebrow}>风格感预览</p>
                    <h3 className={styles.previewHeadline}>{profile.name || '待解析姓名'}</h3>
                    <p className={styles.previewRole}>{profile.role || '解析出你的职业方向'}</p>
                    <p className={styles.previewSummary}>{profile.summary || '选择风格后，站点会和解析结果保持一致。'}</p>
                    <div className={styles.previewTagRow}>
                      {(profile.skills.slice(0, 4).length > 0 ? profile.skills : ['风格预览']).slice(0, 4).map((skill) => (
                        <span key={skill} className={styles.previewTag}>{skill}</span>
                      ))}
                    </div>
                  </div>
                </div>
              </div>

              <div className={styles.stepActions}>
                <button type="button" className={`${styles.btn} ${styles.btnSecondary}`} onClick={() => goToStep(2)}>
                  ← 返回解析
                </button>
                <button type="button" className={`${styles.btn} ${styles.btnPrimary}`} onClick={handleGenerate} disabled={isGenerating}>
                  {isGenerating ? '生成中…' : '生成完整页面 →'}
                </button>
              </div>
            </div>
          </section>

          <section className={styles.stepSlide}>
            <div className={styles.container}>
              <p className={styles.sectionLabel}>STEP 4</p>
              <h2 className={styles.sectionTitle}>预览与下载</h2>
              <p className={styles.sectionSubtitle}>
                这里会直接展示你生成后的站点效果，确认无误后即可下载成完整 HTML 文件。
              </p>

              <div className={styles.previewFrame}>
                <div className={styles.previewBar}>
                  <div className={styles.previewDots}>
                    <span />
                    <span />
                    <span />
                  </div>
                  <div className={styles.previewUrl}>{generatedHtml ? 'your-name.personal-site.com' : '生成成功后会在这里展示站点效果'}</div>
                </div>
                <iframe title="Generated site preview" className={styles.previewIframe} srcDoc={previewDoc} />
              </div>

              <div className={styles.stepActions}>
                <button type="button" className={`${styles.btn} ${styles.btnSecondary}`} onClick={() => goToStep(3)}>
                  ← 更换风格
                </button>
                <button
                  type="button"
                  className={`${styles.btn} ${styles.btnPrimary}`}
                  onClick={() => {
                    const blob = new Blob([generatedHtml], { type: 'text/html' });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = 'personal-ip-site.html';
                    a.click();
                    URL.revokeObjectURL(url);
                  }}
                  disabled={!generatedHtml}
                >
                  下载 HTML 文件
                </button>
              </div>
            </div>
          </section>
        </div>
      </div>

      <footer className={styles.footer}>
        <div className={styles.container}>
          <p>Personal IP Site Generator · Diaolong 叙事工程 驱动</p>
        </div>
      </footer>

      <div className={`${styles.toast} ${toastVisible ? styles.show : ''}`}>{toastMsg}</div>
    </div>
  );
}
